# Generated by Django 6.0.3 on 2026-03-30 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shortener', '0002_shorturl_expires_at_shorturl_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortener.shorturl')),
            ],
        ),
    ]
