# Generated by Django 6.0.3 on 2026-03-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
