# Generated by Django 6.0.3 on 2026-03-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_shorturl_expires_at_shorturl_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='custom_alias',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
