# Generated by Django 6.0.3 on 2026-04-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_shorturl_custom_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
