# Generated by Django 6.0.3 on 2026-04-01 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_shorturl_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='custom_alias',
        ),
    ]
