# Generated by Django 6.0.3 on 2026-04-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_remove_shorturl_custom_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='custom_alias',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
