# Generated by Django 6.0.3 on 2026-04-03 05:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_shorturl_custom_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
